### ISSUE TITLE
builder() function S4 class issue

### ISSUE THREAD

**Issue by cgonza12** [STATWORX/bounceR#1]
Really love the idea for this package. Been having fun playing with some of the test data functions, but I noticed a snag when I tried to use the builder() function. 

```
test_df <- sim_data()

# feature selection
sel <- featureSelection(df = test_df, #this is out of date, needed to change to "data = "
                        target = "y",
                        index = NULL,
                        method = "randomboost",
                        n_cores = 1)
# extract one feature
form <- builder(object = sel, n_features = 1)
```
Throws this error
`Error in object[["stability"]] : this S4 class is not subsettable
`

Looking at the function definition, it seems like it's just a syntax issue with S4. `sel@stability[,'feature']` works fine so I basically did a find and replace on "object[[]]" in the function and it seemed to work okay.

`myBuilder <- function (object, n_features = 5) 
{
  if (!class(object) == "sel_obj") 
    stop(paste0("This function only works with objects of type ", 
                sQuote("sel_obj"), "!"))
  if (n_features > length(pull(object@stability[, "feature"]))) {
    n_features <- length(pull(object@stability[, "feature"]))
    warning(paste0("Seems like you chose too many features. Try to reduce ", 
                   sQuote("n_features"), ". Using all features: ", 
                   n_features))
  }
  form <- as.formula(paste(object@setup[["target"]], 
                           "~", paste(pull(object@stability[, "feature"][1:n_features, 
                                                                              ]), collapse = "+"), sep = ""))
  return(form)
}

form <- myBuilder(object = sel, n_features = 10)

> form
y ~ noise199 + noise053 + noise119 + noise182 + noise095 + noise009 + 
    noise197 + noise061 + noise091 + noise198

`

I'm not a github pro by any means, in fact I've never submitted an issue or suggestion on someone's code before. Hopefully I haven't committed some cardinal sin with this issue post, but this is as an awesome package and it seemed like this small tweak worked. Hope this is helpful. Great work so far will be following to see how this package develops!

**Comment by ghost** [comment]
Thank you very much for making me aware of this. We are working on a new version with some new - hopefully cool - features. I will work in your solution as soon as I can.

Cheers,
Lukas

**Comment by ghost** [comment]
@cgonza12 I fixed it and it should work now. I will close this issue now. Thanks again for having fun with the package and playing around with it.

Cheers,
Lukas
