### ISSUE TITLE
Package 'bounceR' requires R >= 3.4.3

### ISSUE THREAD

**Issue by jbkunst** [STATWORX/bounceR#2]
Hi! Thanks for the package.

Is that requiriment really necessary?

```r
> devtools::install_github("STATWORX/bounceR")

ERROR: this R is version 3.4.1, package 'bounceR' requires R >= 3.4.3
nstallation failed: Command failed (1)
```

**Comment by ghost** [comment]
@jbkunst yes it is, at least for now. We are currently testing the dependencies.

If it is alright with you, I'd close the issue for now. In our next iteration, we might chance this, for now, though we can't.

Best,
Lukas
