### ISSUE TITLE
Tree base learner not working

### ISSUE THREAD

**Issue by stratonx** [STATWORX/bounceR#3]
Hi,

Could you please have a look at the tree base learner? I fit a regression problem into featureSelection function, however it complains:
Error in paste("In iteration", i, "I could not fit a model in round", :
object 'ii' not found

After further checking, the problem seems comes from below script:
mboost::gamboost(as.formula(paste(target, "~", ".", sep = "")),
data = df_mirrored_model,
control = mboost::boost_control(mstop = boosting[["mstop"]], nu = boosting[["nu"]]),
baselearner = c("btree"))

It will throw an error msg:
Error in get(baselearner, mode = "function", envir = parent.frame()) :
object 'btree' of mode 'function' was not found

**Comment by ghost** [comment]
Hey @saianger,

thank you so much for the issue. The first one indeed is a bug and I fixed it. I will be committing the revised version today. 

For the second one, I am afraid, I cannot do much without a reproducible example. I did not get this error.

Would you be so kind as to share your script?

Cheers,
Lukas
